apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: beacon
  namespace: beacon
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: beacon.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: beacon
                port:
                  number: 80
  tls:
    - hosts:
        - beacon.example.com
      secretName: beacon-tls
